-- pg_turbovec v0.5.0 — Phase 5: pgvector-parity helpers and JSONB casts.
--
-- Reference mirror; authoritative SQL is generated by
-- `cargo pgrx schema`.

SET search_path = turbovec, public;

-- ===================================================================
-- Slicing
-- ===================================================================

-- subvector(v tvector, start integer, length integer) RETURNS tvector
--   1-indexed slice, mirrors pgvector's `subvector`.

-- ===================================================================
-- JSONB I/O
-- ===================================================================

-- tvector_to_jsonb(tvector) RETURNS jsonb
-- jsonb_to_tvector(jsonb)   RETURNS tvector
-- CREATE CAST (tvector AS jsonb) WITH FUNCTION tvector_to_jsonb(tvector);
-- CREATE CAST (jsonb   AS tvector) WITH FUNCTION jsonb_to_tvector(jsonb);

-- ===================================================================
-- Constructors and assertions
-- ===================================================================

-- tvector_zeros(integer) RETURNS tvector
-- tvector_check_dim(tvector, integer) RETURNS tvector
-- tvector_to_text(tvector) RETURNS text
