-- pg_turbovec upgrade 2.10.1 -> 2.10.2
-- Run automatically by `ALTER EXTENSION pg_turbovec UPDATE TO '2.10.2';`.
--
-- No new or changed SQL objects: this release is documentation plus a
-- build-time NOTICE. No wire-format change (stays v8), no REINDEX, index
-- bytes unchanged. Intentionally empty apart from this comment.
